### ISSUE TITLE
goctl页面图片失效

### ISSUE THREAD

**Issue by auula** [zeromicro/go-zero-pages#2]
这个页面图片加载失败:[https://go-zero.dev/cn/goctl-commands.html](https://go-zero.dev/cn/goctl-commands.html)
<img width="940" alt="image" src="https://user-images.githubusercontent.com/38412458/158066767-ca6fa6f8-3baa-4454-84ec-fea143ce4e12.png">

评论的gittalk也失效。

**Comment by kevwan** [comment]
where is the gittalk?

**Comment by auula** [comment]
hahaha，gittalk issue [https://github.com/zeromicro/go-zero-pages/issues/1](https://github.com/zeromicro/go-zero-pages/issues/1)
